import express from 'express'; import path from 'node:path'; import fs from 'node:fs'; import { fileURLToPath } from 'node:url'; import { taskInput, Recurrence } from './domain.js'; import { SchedulerRepository } from './repository.js'; import { Notifier } from './notifications.js'
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'); const env={...process.env}; const envFile=path.join(root,'.env'); if(fs.existsSync(envFile)) for(const line of fs.readFileSync(envFile,'utf8').split('\n')) { const [k,...v]=line.split('='); if(k&&v.length&&!env[k]) env[k]=v.join('=').trim() }
const repo=new SchedulerRepository(path.resolve(root,env.DB_PATH||'data/scheduler.db')); const notifier=new Notifier(env,repo); const app=express(); app.use(express.json());
const wrap=fn=>(req,res)=>{try{fn(req,res)}catch(e){res.status(400).json({error:e.message})}}
app.get('/api/health',(q,s)=>s.json({ok:true,channels:{gotify:notifier.configured('gotify'),email:notifier.configured('email'),sms:notifier.configured('sms')}}));
app.get('/api/dashboard',(q,s)=>s.json(repo.dashboard())); app.get('/api/tasks/:id',(q,s)=>{const t=repo.get(q.params.id);t?s.json({...t,history:repo.history(t.id)}):s.sendStatus(404)});
app.post('/api/tasks',wrap((q,s)=>s.status(201).json(repo.create(taskInput({...q.body,timezone:repo.preference('timezone',env.HOUSEHOLD_TIMEZONE||'UTC')}))))); app.put('/api/tasks/:id',wrap((q,s)=>{const task=repo.update(q.params.id,taskInput({...q.body,timezone:repo.preference('timezone',env.HOUSEHOLD_TIMEZONE||'UTC')}));task?s.json(task):s.sendStatus(404)})); app.delete('/api/tasks/:id',(q,s)=>repo.delete(q.params.id)?s.sendStatus(204):s.sendStatus(404));
app.delete('/api/tasks/:taskId/history/:historyId',(q,s)=>repo.deleteHistory(q.params.taskId,q.params.historyId)?s.sendStatus(204):s.sendStatus(404));
app.post('/api/tasks/:id/action',wrap((q,s)=>{const t=repo.get(q.params.id);if(!t)return s.sendStatus(404);const action=String(q.body.action||'');let dueAt;if(action==='snoozed'){const until=new Date(q.body.until);if(Number.isNaN(until.getTime()))throw new Error('Choose when to snooze until.');dueAt=until.toISOString()}else if(action==='skipped'){dueAt=new Recurrence(t.unit,t.interval,t.customCron).nextDue(new Date().toISOString())}else throw new Error('Choose a valid action');const history=repo.applyAction(t.id,action,{dueAt,note:q.body.note||''});s.json({...repo.get(t.id),historyAction:history})})); app.post('/api/tasks/:id/actions/:actionId/undo',wrap((q,s)=>{const t=repo.get(q.params.id);if(!t)return s.sendStatus(404);s.json(repo.undoAction(t.id,Number(q.params.actionId)))})); app.post('/api/tasks/:id/complete',wrap((q,s)=>{const t=repo.get(q.params.id);if(!t) return s.sendStatus(404); const at=new Date().toISOString(), recurrence=new Recurrence(t.unit,t.interval,t.customCron), streak=Recurrence.nextStreak({streak:t.streak,dueAt:t.dueAt,completedAt:at});s.json(repo.complete(t.id,at,recurrence.nextDue(at),streak,String(q.body.note||'')))}));
app.get('/api/preferences',(q,s)=>s.json({emailTo:repo.preference('emailTo',env.DEFAULT_EMAIL_TO||''),smsTo:repo.preference('smsTo',env.DEFAULT_SMS_TO||''),smsProvider:repo.preference('smsProvider',env.SMS_PROVIDER||'gateway'),publicUrl:repo.preference('publicUrl',env.PUBLIC_URL||'')})); app.put('/api/preferences',wrap((q,s)=>{for(const k of ['emailTo','smsTo','publicUrl']) if(typeof q.body[k]==='string') repo.setPreference(k,q.body[k].trim()); if(['gateway','twilio'].includes(q.body.smsProvider)) repo.setPreference('smsProvider',q.body.smsProvider); s.json({ok:true})}));
app.use(express.static(path.join(root,'dist'),{index:false,maxAge:'1y',immutable:true})); app.get('/{*path}',(q,s)=>{s.set('Cache-Control','no-store');s.sendFile(path.join(root,'dist','index.html'))}); setInterval(()=>notifier.check(),60000).unref(); notifier.check(); app.listen(Number(env.PORT||8091),()=>console.log(`Scheduler is ready on http://localhost:${env.PORT||8091}`));
