import nodemailer from 'nodemailer'
export class Notifier {
  constructor(env, repo) { this.env=env; this.repo=repo; this.mail=env.SMTP_USER&&env.SMTP_PASSWORD ? nodemailer.createTransport({host:env.SMTP_HOST||'smtp.gmail.com',port:Number(env.SMTP_PORT||465),secure:Number(env.SMTP_PORT||465)===465,auth:{user:env.SMTP_USER,pass:env.SMTP_PASSWORD}}) : null }
  destinationText(channel) { return this.repo.preference(channel === 'sms' ? 'smsTo' : 'emailTo', channel === 'sms' ? this.env.DEFAULT_SMS_TO : this.env.DEFAULT_EMAIL_TO) }
  smsProvider() { return this.repo.preference('smsProvider', this.env.SMS_PROVIDER || 'gateway') }
  destinations(channel) {
    const gateway = this.env.SMS_GATEWAY_DOMAIN || 'vtext.com'
    return [...new Set(this.destinationText(channel).split(/[\n,;]+/).map(value => value.trim().toLowerCase()).map(value => channel === 'sms' && /^\+?1?\D*(\d\D*){10}$/.test(value) ? `${value.replace(/\D/g,'').slice(-10)}@${gateway}` : value).filter(value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)))]
  }
  smsTargets() { return [...new Set(this.destinationText('sms').split(/[\n,;]+/).map(value => value.replace(/\D/g,'')).filter(value => value.length === 10).map(value => `+1${value}`))] }
  taskUrl(task) { try { const url = new URL(this.repo.preference('publicUrl', this.env.PUBLIC_URL || '')); url.searchParams.set('task', task.id); return url.toString() } catch { return '' } }
  message(task) { return `Time for ${task.title}. Keep the streak alive — you’re on ${task.streak || 0}.${this.taskUrl(task) ? ` Open Rhythm: ${this.taskUrl(task)}` : ''}` }
  async sendSms(message) { if (this.smsProvider() === 'twilio') { const url=`https://api.twilio.com/2010-04-01/Accounts/${this.env.TWILIO_ACCOUNT_SID}/Messages.json`; for (const to of this.smsTargets()) { const response=await fetch(url,{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${this.env.TWILIO_ACCOUNT_SID}:${this.env.TWILIO_AUTH_TOKEN}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({To:to,From:this.env.TWILIO_FROM,Body:message})}); if(!response.ok) throw new Error(`Twilio returned ${response.status}`) } return } await this.mail.sendMail({from:this.env.EMAIL_FROM||this.env.SMTP_USER,to:this.destinations('sms'),subject:'Rhythm reminder',text:message}) }
  async send(task, channel) { if (!this.repo.markSent(task.id,channel,task.dueAt)) return false; const title=`${task.emoji} ${task.title} is due`; const message=this.message(task); try { if(channel==='gotify') await fetch(`${this.env.GOTIFY_URL}/message?token=${this.env.GOTIFY_TOKEN}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,message,priority:5})}); if(channel==='email') await this.mail.sendMail({from:this.env.EMAIL_FROM||this.env.SMTP_USER,to:this.destinations('email'),subject:title,text:message}); if(channel==='sms') await this.sendSms(message); return true } catch (e) { console.error(`notification ${channel} failed`,e.message); return false } }
  async check() { for(const task of this.repo.due()) for(const channel of ['gotify','email','sms']) if(task.channels[channel] && this.configured(channel)) await this.send(task,channel) }
  configured(channel) { if(channel==='gotify') return Boolean(this.env.GOTIFY_URL&&this.env.GOTIFY_TOKEN); if(channel==='email') return Boolean(this.mail&&this.destinations('email').length); return this.smsProvider()==='twilio' ? Boolean(this.env.TWILIO_ACCOUNT_SID&&this.env.TWILIO_AUTH_TOKEN&&this.env.TWILIO_FROM&&this.smsTargets().length) : Boolean(this.mail&&this.destinations('sms').length) }
}
