import Database from 'better-sqlite3'
import fs from 'node:fs'; import path from 'node:path'
import { householdInsights } from './insights.js'
export class SchedulerRepository {
  constructor(dbPath) { fs.mkdirSync(path.dirname(dbPath), { recursive: true }); this.db = new Database(dbPath); this.db.pragma('journal_mode = WAL'); this.migrate() }
  migrate() { this.db.exec(`CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY, title TEXT NOT NULL, emoji TEXT, color TEXT, notes TEXT, unit TEXT NOT NULL, interval INTEGER NOT NULL, due_at TEXT NOT NULL, all_day INTEGER NOT NULL DEFAULT 1, custom_cron TEXT NOT NULL DEFAULT '', streak INTEGER DEFAULT 0, best_streak INTEGER DEFAULT 0, channels TEXT NOT NULL, archived INTEGER DEFAULT 0, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS completions(id INTEGER PRIMARY KEY, task_id INTEGER NOT NULL, completed_at TEXT NOT NULL, note TEXT, action TEXT NOT NULL DEFAULT 'completed', due_at_before TEXT, undone_at TEXT, FOREIGN KEY(task_id) REFERENCES tasks(id)); CREATE TABLE IF NOT EXISTS sent_notifications(id INTEGER PRIMARY KEY, task_id INTEGER NOT NULL, channel TEXT NOT NULL, due_at TEXT NOT NULL, sent_at TEXT NOT NULL, UNIQUE(task_id,channel,due_at)); CREATE TABLE IF NOT EXISTS preferences(key TEXT PRIMARY KEY, value TEXT NOT NULL);`); const cols=this.db.prepare("PRAGMA table_info(tasks)").all(); if (!cols.some(column => column.name === 'all_day')) this.db.exec('ALTER TABLE tasks ADD COLUMN all_day INTEGER NOT NULL DEFAULT 1'); if (!cols.some(column => column.name === 'custom_cron')) this.db.exec("ALTER TABLE tasks ADD COLUMN custom_cron TEXT NOT NULL DEFAULT ''"); if (!this.db.prepare("PRAGMA table_info(completions)").all().some(column => column.name === 'action')) this.db.exec("ALTER TABLE completions ADD COLUMN action TEXT NOT NULL DEFAULT 'completed'"); for (const c of ['due_at_before','undone_at']) if (!this.db.prepare('PRAGMA table_info(completions)').all().some(x=>x.name===c)) this.db.exec(`ALTER TABLE completions ADD COLUMN ${c} TEXT`) }
  task(row) { return row && ({ ...row, interval: Number(row.interval), allDay: Boolean(row.all_day), customCron: row.custom_cron, streak: Number(row.streak), bestStreak: Number(row.best_streak), dueAt: row.due_at, createdAt: row.created_at, channels: JSON.parse(row.channels) }) }
  list() { return this.db.prepare('SELECT * FROM tasks WHERE archived=0 ORDER BY due_at').all().map(x => this.task(x)) }
  get(id) { return this.task(this.db.prepare('SELECT * FROM tasks WHERE id=?').get(id)) }
  create(x) { const r=this.db.prepare('INSERT INTO tasks(title,emoji,color,notes,unit,interval,due_at,all_day,custom_cron,channels,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(x.title,x.emoji,x.color,x.notes,x.recurrence.unit,x.recurrence.interval,x.dueAt,x.allDay?1:0,x.recurrence.customCron || '',JSON.stringify(x.channels),new Date().toISOString()); return this.get(r.lastInsertRowid) }
  update(id,x) { this.db.prepare('UPDATE tasks SET title=?,emoji=?,color=?,notes=?,unit=?,interval=?,due_at=?,all_day=?,custom_cron=?,channels=? WHERE id=?').run(x.title,x.emoji,x.color,x.notes,x.recurrence.unit,x.recurrence.interval,x.dueAt,x.allDay?1:0,x.recurrence.customCron || '',JSON.stringify(x.channels),id); return this.get(id) }
  delete(id) { const tx=this.db.transaction(()=>{this.db.prepare('DELETE FROM completions WHERE task_id=?').run(id);this.db.prepare('DELETE FROM sent_notifications WHERE task_id=?').run(id);return this.db.prepare('DELETE FROM tasks WHERE id=?').run(id).changes > 0});return tx() }
  applyAction(id, action, { dueAt, note='' }) { const tx=this.db.transaction(()=>{const task=this.get(id); if(!task || !['skipped','snoozed'].includes(action)) throw new Error('Choose a valid action'); const r=this.db.prepare("INSERT INTO completions(task_id,completed_at,note,action,due_at_before) VALUES(?,?,?,?,?)").run(id,new Date().toISOString(),String(note),action,task.dueAt); this.db.prepare('UPDATE tasks SET due_at=? WHERE id=?').run(dueAt,id); return this.db.prepare('SELECT * FROM completions WHERE id=?').get(r.lastInsertRowid)}); return tx() }
  undoAction(id, actionId) { const tx=this.db.transaction(()=>{const a=this.db.prepare("SELECT * FROM completions WHERE id=? AND task_id=? AND action IN ('skipped','snoozed') AND undone_at IS NULL").get(actionId,id); if(!a) throw new Error('That action can’t be undone.'); this.db.prepare('UPDATE tasks SET due_at=? WHERE id=?').run(a.due_at_before,id); this.db.prepare('UPDATE completions SET undone_at=? WHERE id=?').run(new Date().toISOString(),actionId); return this.get(id)}); return tx() }
  recordAction(id, action, at=new Date().toISOString(), note='') { if (!['skipped','snoozed'].includes(action)) throw new Error('Choose a valid action'); this.db.prepare('INSERT INTO completions(task_id,completed_at,note,action) VALUES(?,?,?,?)').run(id,at,note,action); return this.get(id) }
  complete(id, completedAt, nextDue, streak, note='') { const tx=this.db.transaction(()=>{const existing=this.db.prepare("SELECT 1 FROM completions WHERE task_id=? AND action='completed' AND date(completed_at)=date(?)").get(id,completedAt);if(existing) return this.get(id);this.db.prepare("INSERT INTO completions(task_id,completed_at,note,action) VALUES(?,?,?,'completed')").run(id,completedAt,note);this.db.prepare('UPDATE tasks SET due_at=?,streak=?,best_streak=MAX(best_streak,?) WHERE id=?').run(nextDue,streak,streak,id);return this.get(id)});return tx() }
  deleteHistory(taskId, historyId) { const tx=this.db.transaction(()=>{const history=this.db.prepare('SELECT action FROM completions WHERE id=? AND task_id=?').get(historyId,taskId);if(!history)return false;this.db.prepare('DELETE FROM completions WHERE id=? AND task_id=?').run(historyId,taskId);if(history.action==='completed')this.db.prepare('UPDATE tasks SET streak=MAX(streak-1,0),best_streak=MAX(best_streak-1,0) WHERE id=?').run(taskId);return true});return tx() }
  history(id) { return this.db.prepare('SELECT * FROM completions WHERE task_id=? ORDER BY completed_at DESC LIMIT 80').all(id) }
  dashboard(at = new Date()) { const tasks=this.list(), timezone=this.preference('timezone','UTC'), localDay=value=>new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)).replace(/\//g,'-'), today=localDay(at), completions=this.db.prepare('SELECT c.*,t.title,t.emoji FROM completions c JOIN tasks t ON t.id=c.task_id ORDER BY completed_at DESC LIMIT 200').all(); return { tasks, overdue:tasks.filter(t=>localDay(t.dueAt)<today), today:tasks.filter(t=>localDay(t.dueAt)===today), next:tasks.filter(t=>localDay(t.dueAt)>today), completions:completions.slice(0,20), insights:householdInsights({ now: at, tasks, history: completions }) } }
  due() { return this.list().filter(t => new Date(t.dueAt) <= new Date()) }
  markSent(id, channel, dueAt) { try { this.db.prepare('INSERT INTO sent_notifications(task_id,channel,due_at,sent_at) VALUES(?,?,?,?)').run(id,channel,dueAt,new Date().toISOString()); return true } catch { return false } }
  preference(key, fallback='') { return this.db.prepare('SELECT value FROM preferences WHERE key=?').get(key)?.value ?? fallback }
  setPreference(key,value) { this.db.prepare('INSERT INTO preferences(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(key,value) }
}
